"""Initial migration - create all tables

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create live_decision_logs table
    op.create_table('live_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'FAILED', 'CANCELLED', 'HOLD', name='decisionstatus'), nullable=True),
    sa.Column('model_provider', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('position_size_usd', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('tier1_target', sa.Float(), nullable=True),
    sa.Column('tier1_ratio', sa.Float(), nullable=True),
    sa.Column('tier2_target', sa.Float(), nullable=True),
    sa.Column('tier2_ratio', sa.Float(), nullable=True),
    sa.Column('tier3_target', sa.Float(), nullable=True),
    sa.Column('tier3_ratio', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_decision_logs_id'), 'live_decision_logs', ['id'], unique=False)
    op.create_index('idx_decision_logs_created_at', 'live_decision_logs', ['created_at'], unique=False)
    op.create_index('idx_decision_logs_symbol_status', 'live_decision_logs', ['symbol', 'status'], unique=False)
    op.create_index('idx_decision_logs_symbol_status_created_at', 'live_decision_logs', ['symbol', 'status', 'created_at'], unique=False)

    # Create live_orders table
    op.create_table('live_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'LONG', 'SHORT', name='orderside'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filled_amount', sa.Float(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('ft_order_id', sa.Integer(), nullable=True),
    sa.Column('ft_pair', sa.String(length=32), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_orders_id'), 'live_orders', ['id'], unique=False)
    op.create_index('idx_orders_created_at', 'live_orders', ['created_at'], unique=False)
    op.create_index('idx_orders_decision_id', 'live_orders', ['decision_id'], unique=False)
    op.create_index('idx_orders_symbol_status', 'live_orders', ['symbol', 'status'], unique=False)
    op.create_index('idx_orders_symbol_status_created_at', 'live_orders', ['symbol', 'status', 'created_at'], unique=False)

    # Create live_tiers table
    op.create_table('live_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['live_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_tiers_id'), 'live_tiers', ['id'], unique=False)

    # Create live_order_logs table
    op.create_table('live_order_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('from_status', sa.Enum('OPEN', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('OPEN', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['live_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_order_logs_id'), 'live_order_logs', ['id'], unique=False)

    # Create live_modification_log table
    op.create_table('live_modification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['live_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_modification_log_id'), 'live_modification_log', ['id'], unique=False)

    # Create trade_operation_log table
    op.create_table('trade_operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ft_order_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_operation_log_id'), 'trade_operation_log', ['id'], unique=False)
    op.create_index('idx_trade_logs_created_at', 'trade_operation_log', ['created_at'], unique=False)
    op.create_index('idx_trade_logs_symbol', 'trade_operation_log', ['symbol'], unique=False)

    # Create last_decisions table
    op.create_table('last_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'FAILED', 'CANCELLED', 'HOLD', name='decisionstatus'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('position_size_usd', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_last_decisions_id'), 'last_decisions', ['id'], unique=False)
    op.create_index('idx_last_decisions_updated_at', 'last_decisions', ['updated_at'], unique=False)

    # Create additional indexes
    op.create_index('idx_tiers_order_id_tier', 'live_tiers', ['order_id', 'tier'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tiers_order_id_tier', table_name='live_tiers')
    op.drop_index(op.f('ix_last_decisions_id'), table_name='last_decisions')
    op.drop_index('idx_last_decisions_updated_at', table_name='last_decisions')
    op.drop_table('last_decisions')
    op.drop_index(op.f('ix_trade_operation_log_id'), table_name='trade_operation_log')
    op.drop_index('idx_trade_logs_symbol', table_name='trade_operation_log')
    op.drop_index('idx_trade_logs_created_at', table_name='trade_operation_log')
    op.drop_table('trade_operation_log')
    op.drop_index(op.f('ix_live_modification_log_id'), table_name='live_modification_log')
    op.drop_table('live_modification_log')
    op.drop_index(op.f('ix_live_order_logs_id'), table_name='live_order_logs')
    op.drop_table('live_order_logs')
    op.drop_index(op.f('ix_live_tiers_id'), table_name='live_tiers')
    op.drop_table('live_tiers')
    op.drop_index('idx_orders_symbol_status_created_at', table_name='live_orders')
    op.drop_index('idx_orders_decision_id', table_name='live_orders')
    op.drop_index('idx_orders_symbol_status', table_name='live_orders')
    op.drop_index('idx_orders_created_at', table_name='live_orders')
    op.drop_index(op.f('ix_live_orders_id'), table_name='live_orders')
    op.drop_table('live_orders')
    op.drop_index('idx_decision_logs_symbol_status_created_at', table_name='live_decision_logs')
    op.drop_index('idx_decision_logs_symbol_status', table_name='live_decision_logs')
    op.drop_index('idx_decision_logs_created_at', table_name='live_decision_logs')
    op.drop_index(op.f('ix_live_decision_logs_id'), table_name='live_decision_logs')
    op.drop_table('live_decision_logs')
    # ### end Alembic commands ###